version: "3"

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
#    volumes:
#      - "/home/superman/mongo_data:/data/db"
  zookeeper:
    image: docker.io/bitnami/zookeeper:3
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: docker.io/bitnami/kafka:2
    ports:
      - "9094:9094"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=INTERNAL://kafka:9092,OUTSIDE://kafka:9094
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka:9092,OUTSIDE://localhost:9094
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_LOG_RETENTION_MINUTES=2
    depends_on:
      - zookeeper

#  kafka-quickstart:
#    image: localhost:5000/kafka-quickstart:latest
#    ports:
#      - "8080:8080"

#    environment:
#      - kafka.bootstrap.servers=kafka:9092
#    depends_on:
#      - kafka

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local

