kafka:
  enabled: true
  bootstrapAddress: kafka:9092
  topic: test-topic
  group-id: test-group-id
  batch: true
  concurrency: 2
  producer:
    refresh-initial-delay: PT0S
    refresh-delay: PT10S

mongo:
  enabled: true
  address: mongodb
  port: 27017
  database-name: playground
